### PR TITLE
Integration of OSB endpoint

### PR DESCRIPTION
**Pull request by FlorentinGarnier**

### CODE REVIEW

**Review by Prometee — APPROVED** [review]

**Review by Prometee — CHANGES_REQUESTED** [review]
It could be interesting to also edit the `README.md` to show that the endpoint can also be part of the gateway creation and that this Payum gateway is also supporting OSB now.

**Review by Prometee — APPROVED** [review]

**Comment by Prometee** [comment]
@ekyna ready to be merged 😊

**Comment by ekyna** [comment]
Thx @FlorentinGarnier and @Prometee

**Comment by Prometee** [comment]
@ekyna will you be able to tag a new release (v1.6.1 maybe) we need it for the Sylius plugin : https://github.com/kiboko-labs/payzen-bundle/pull/3

**Comment by ekyna** [comment]
@Prometee Already pushed [1.6.5 tag](https://github.com/ekyna/PayumPayzen/releases/tag/1.6.5). Is that ok ?

**Comment by Prometee** [comment]
@ekyna Thank you very much it's perfect 😉

**Pull request merged**
